//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecART.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.BookLoans = new HashSet<BookLoans>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> YearPublished { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> Available { get; set; }
    
        public virtual ICollection<BookLoans> BookLoans { get; set; }
        public virtual Departments Departments { get; set; }
    }
}
