//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecART.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLoans
    {
        public int LoanID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual LibraryCards LibraryCards { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
