//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecART.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryCards
    {
        public LibraryCards()
        {
            this.BookLoans = new HashSet<BookLoans>();
        }
    
        public int CardID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    
        public virtual ICollection<BookLoans> BookLoans { get; set; }
        public virtual Readers Readers { get; set; }
    }
}
